using UnityEngine;

namespace Observer.Ex3
{
    public class Observer : MonoBehaviour
    {
        [SerializeField] private Subject subjectToObserve;

        private void OnThingHappened()
        {
            Debug.Log("Observer responds");
        }

        private void Awake()
        {
            if (subjectToObserve != null)
            {
                subjectToObserve.ThingHappened += OnThingHappened;
            }
        }

        private void OnDestroy()
        {
            if (subjectToObserve != null)
            {
                subjectToObserve.ThingHappened -= OnThingHappened;
            }
        }
    }
}